projectName: monitoring
nameSpace: main
app: kubestatemetrics

replicaSet: 1
minReplicas: 1
maxReplicas: 3
averageUtilization: 70


ContainerService:
  type: ClusterIP  # {{ .Values.ContainerService.type }}
  port: 8080      # {{ .Values.ContainerService.port }}


dockerImage: k8s.gcr.io/kube-state-metrics/kube-state-metrics         # {{ .Values.dockerImage }}
dockerVersion: v2.2.4                     # {{ .Values.dockerVersion }}


