apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
