apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  labels:
    app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
spec:
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
    spec:
      serviceAccountName: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
      containers:
      - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
        image: {{ .Values.dockerImage }}:{{ .Values.dockerVersion }}
        ports:
        - containerPort: {{ .Values.ContainerService.port }}
