apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
  labels:
    app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
  template:
    metadata:
      labels:
        app: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
    spec:  
      initContainers:
      - name: volume-permissions
        image: busybox
        command: ['sh', '-c', 'chown -R 472:472 /var/lib/grafana']
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana      
      containers:
      - name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
        image: {{ .Values.dockerImage }}:{{ .Values.dockerVersion }}
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: monitoring-main-prometheus-pvc        
     