apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }}-cm
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    rule_files:
      - "/etc/prometheus/alert.rules"
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'node-exporter'
        static_configs:
        - targets: ['{{ .Values.projectName }}-{{ .Values.nameSpace }}-nodeexporter:9100']
