apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }}-pvc
spec:
  storageClassName: do-block-storage  # Just the storage class name
  accessModes:
    - ReadWriteOnce  # Access mode is a separate field
  resources:
    requests:
      storage: 10Gi






      