apiVersion: v1
kind: Service
metadata:
  name:  {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 
  namespace: {{ .Values.projectName }}-{{ .Values.nameSpace }}
spec:
  type: {{ .Values.ContainerService.type }}
  ports:
    - port: {{ .Values.ContainerService.port }}
      targetPort: {{ .Values.ContainerService.port }}
      protocol: TCP
      name: http
  selector:
    app:  {{ .Values.projectName }}-{{ .Values.nameSpace }}-{{ .Values.app }} 

