projectName: monitoring
nameSpace: main
app: grafana

replicaSet: 1
minReplicas: 1
maxReplicas: 3
averageUtilization: 70


ContainerService:
  type: ClusterIP  # {{ .Values.ContainerService.type }}
  port: 3000       # {{ .Values.ContainerService.port }}


domainName: oostvoort.work                # {{ .Values.domainName }}

subDomainName: 
  grafana: monitor.aw                    # {{ .Values.subDomainName.prometheus }}

dockerImage: grafana/grafana              # {{ .Values.dockerImage }}
dockerVersion: latest                     # {{ .Values.dockerVersion }}